### ISSUE TITLE
Seeing multiple errors in ReactNativeMeshGradient.swift when trying to build

### ISSUE THREAD

**Issue by crosswi** [adrian-koczen/react-native-mesh-gradient#1]
Steps to replicate:
- Run `yarn add react-native-mesh-gradient && cd ios && pod install && cd ..`
- Attempt to build native project

react: "18.3.1",
react-native: "0.75.2",
react-native-mesh-gradient: "^1.0.0"

<img width="1141" alt="Screenshot 2024-08-21 at 2 22 22 PM" src="https://github.com/user-attachments/assets/3d6a62d1-3768-4af9-95f3-1edba8e21bfc">

**Comment by adrian-koczen** [comment]
Hi @CrossWI. It's expo or bare react native project?

**Comment by crosswi** [comment]
Hi @adrian-koczen, it's a bare react native project. Adding the changes in my PR fixed the issue for me

**Comment by adrian-koczen** [comment]
Thanks @crosswi for fixing issue. Version 1.0.1 is ready.
